<?php

include 'lang/English/language.php';

$files = array(
	'backstage/about.php',
	'backstage/appearance.php',
	'backstage/bans.php',
	'backstage/board.php',
	'backstage/censoring.php',
	'backstage/database.php',
	'backstage/email.php',
	'backstage/features.php',
	'backstage/footer.php',
	'backstage/groups.php',
	'backstage/header.php',
	'backstage/index.php',
	'backstage/loader.php',
	'backstage/login.php',
	'backstage/maintenance.php',
	'backstage/menu.php',
	'backstage/moderate.php',
	'backstage/permissions.php',
	'backstage/prune.php',
	'backstage/ranks.php',
	'backstage/registration.php',
	'backstage/reports.php',
	'backstage/settings.php',
	'backstage/system.php',
	'backstage/theme.php',
	'backstage/tools.php',
	'backstage/update.php',
	'backstage/users.php',
	'buildgettext.php',
	'cache/cache_bans.php',
	'cache/cache_config.php',
	'cache/cache_users_info.php',
	'config.php',
	'db_update.php',
	'delete.php',
	'edit.php',
	'extern.php',
	'header.php',
	'help.php',
	'inbox.php',
	'include/backstage_functions.php',
	'include/cache.php',
	'include/common.php',
	'include/dblayer/common_db.php',
	'include/dblayer/mysql.php',
	'include/dblayer/mysql_innodb.php',
	'include/dblayer/mysqli.php',
	'include/dblayer/mysqli_innodb.php',
	'include/dblayer/pgsql.php',
	'include/dblayer/sqlite.php',
	'include/draw_functions.php',
	'include/email.php',
	'include/functions.php',
	'include/general_functions.php',
	'include/inbox_functions.php',
	'include/install.php',
	'include/l10n.php',
	'include/me_functions.php',
	'include/parser.php',
	'include/pomo/MO.php',
	'include/pomo/PO.php',
	'include/pomo/Streams/CachedFileReader.php',
	'include/pomo/Streams/CachedIntFileReader.php',
	'include/pomo/Streams/FileReader.php',
	'include/pomo/Streams/Reader.php',
	'include/pomo/Streams/StringReader.php',
	'include/pomo/Translations/EntryTranslations.php',
	'include/pomo/Translations/GettextTranslations.php',
	'include/pomo/Translations/NOOPTranslations.php',
	'include/pomo/Translations/Translations.php',
	'include/pomo/Translations/TranslationsInterface.php',
	'include/search_idx.php',
	'include/srand.php',
	'include/statistic_functions.php',
	'include/utf8/mbstring/core.php',
	'include/utf8/native/core.php',
	'include/utf8/ord.php',
	'include/utf8/str_ireplace.php',
	'include/utf8/str_pad.php',
	'include/utf8/str_split.php',
	'include/utf8/strcasecmp.php',
	'include/utf8/strcspn.php',
	'include/utf8/stristr.php',
	'include/utf8/strrev.php',
	'include/utf8/strspn.php',
	'include/utf8/substr_replace.php',
	'include/utf8/trim.php',
	'include/utf8/ucfirst.php',
	'include/utf8/ucwords.php',
	'include/utf8/utf8.php',
	'include/utf8/utils/ascii.php',
	'include/utf8/utils/bad.php',
	'include/utf8/utils/patterns.php',
	'include/utf8/utils/position.php',
	'include/utf8/utils/specials.php',
	'include/utf8/utils/unicode.php',
	'include/utf8/utils/validation.php',
	'include/version.php',
	'index.php',
	'install.php',
	'lang/English/language.php',
	'login.php',
	'misc.php',
	'new_inbox.php',
	'notifications.php',
	'post.php',
	'profile.php',
	'register.php',
	'search.php',
	'settings.php',
	'themes/Luna/delete.php',
	'themes/Luna/edit.php',
	'themes/Luna/footer.php',
	'themes/Luna/forum.php',
	'themes/Luna/header.php',
	'themes/Luna/help.php',
	'themes/Luna/inbox-delete-post.php',
	'themes/Luna/inbox-delete.php',
	'themes/Luna/inbox-new.php',
	'themes/Luna/inbox-view.php',
	'themes/Luna/inbox.php',
	'themes/Luna/index.php',
	'themes/Luna/information.php',
	'themes/Luna/login.php',
	'themes/Luna/mail.php',
	'themes/Luna/maintenance.php',
	'themes/Luna/me-delete.php',
	'themes/Luna/me-modals.php',
	'themes/Luna/notifications.php',
	'themes/Luna/objects/comment.php',
	'themes/Luna/objects/forum.php',
	'themes/Luna/objects/search-topic.php',
	'themes/Luna/objects/section-info.php',
	'themes/Luna/objects/topic.php',
	'themes/Luna/objects/user.php',
	'themes/Luna/post.php',
	'themes/Luna/profile.php',
	'themes/Luna/register.php',
	'themes/Luna/report.php',
	'themes/Luna/reset.php',
	'themes/Luna/rules.php',
	'themes/Luna/search-advanced.php',
	'themes/Luna/search-results.php',
	'themes/Luna/search.php',
	'themes/Luna/settings.php',
	'themes/Luna/soft.php',
	'themes/Luna/thread.php',
	'themes/Luna/users.php',
	'themes/Random/delete.php',
	'themes/Random/edit.php',
	'themes/Random/footer.php',
	'themes/Random/forum.php',
	'themes/Random/header.php',
	'themes/Random/help.php',
	'themes/Random/inbox-delete-post.php',
	'themes/Random/inbox-delete.php',
	'themes/Random/inbox-new.php',
	'themes/Random/inbox-view.php',
	'themes/Random/inbox.php',
	'themes/Random/index.php',
	'themes/Random/information.php',
	'themes/Random/login.php',
	'themes/Random/mail.php',
	'themes/Random/maintenance.php',
	'themes/Random/me-delete.php',
	'themes/Random/me-modals.php',
	'themes/Random/notifications.php',
	'themes/Random/objects/category.php',
	'themes/Random/objects/comment.php',
	'themes/Random/objects/forum.php',
	'themes/Random/objects/search-topic.php',
	'themes/Random/objects/section-info.php',
	'themes/Random/objects/subforum.php',
	'themes/Random/objects/topic.php',
	'themes/Random/objects/user.php',
	'themes/Random/post.php',
	'themes/Random/profile.php',
	'themes/Random/register.php',
	'themes/Random/report.php',
	'themes/Random/reset.php',
	'themes/Random/rules.php',
	'themes/Random/search-advanced.php',
	'themes/Random/search-results.php',
	'themes/Random/search.php',
	'themes/Random/settings.php',
	'themes/Random/soft.php',
	'themes/Random/style.php',
	'themes/Random/thread.php',
	'themes/Random/users.php',
	'themes/Sunrise/forum.php',
	'themes/Sunrise/header.php',
	'themes/Sunrise/index.php',
	'themes/Sunrise/information.php',
	'themes/Sunrise/objects/category.php',
	'themes/Sunrise/objects/forum.php',
	'themes/Sunrise/objects/subforum.php',
	'themes/Sunrise/thread.php',
	'userlist.php',
	'viewforum.php',
	'viewinbox.php',
	'viewtopic.php'
);

$matches = array();

foreach ( $lang as $slug => $trans ) {
	foreach ( $files as $file ) {
		$s = '$lang[\'' . $slug . '\']';
		$f = file_get_contents( $file );
		$c = substr_count( $f, $s );
		if ( $c ) {
			//$key   = sprintf( "\$lang['%s']", $slug );
			$value = sprintf( "__('%s', 'luna')", $trans );
			$matches[ $file ][ $slug ] = $value;
		}
	}
}

//print_r( $matches );

foreach ( $matches as $file => $replace ) {

	$keys   = array_keys( $replace );
	$keys   = array_map( create_function( '$key', 'return sprintf( "\$lang[\'%s\']", $key );' ), $keys );
	$values = array_values( $replace );

	$f = file_get_contents( $file );
	$f = str_replace( $keys, $values, $f );

	$f = file_put_contents( $file, $f );
}
